const translations = {
    en: {
        title: "Online Voting",
        home: "Home",
        login: "Login",
        signup: "Signup",
        vote: "Vote",
        results: "Results",
        welcome: "Welcome to the Official Online Voting System",
        voter: "Voter",
        candidate: "Candidate",
        admin: "Administrator",
        aadhaar: "Aadhaar Number",
        password: "Password",
        mobile: "Mobile Number",
        submit: "Submit",
        name: "Full Name",
        dob: "Date of Birth",
        party: "Party Name",
        ideology: "Ideology",
        photo: "Upload Photo",
        approve: "Approve",
        reject: "Reject",
        pending: "Pending Requests",
        publish: "Publish Results",
        otp: "Enter OTP",
        verify: "Verify",
        verifyVote: "Verify & Vote",
        alreadyVoted: "You have already voted.",
        votingOpen: "Voting is Open!",
        selectLang: "Select Language",
        candidateId: "Candidate ID",
        email: "Email Address",
        chooseType: "Choose Registration Type",
        voterSignupDesc: "Register to cast your vote.",
        candidateSignupDesc: "Register to contest in elections.",
        loginDesc: "Access your dashboard.",
        resultsPublished: "Election Results Published!",
        resultsPending: "Results are pending... Election in progress.",
        adminDashboard: "Admin Dashboard",
        noData: "No data available.",
        authOptions: "Access Portal",
        authDesc: "Are you a new or existing user?",
        castYourVote: "Cast Your Vote",
        logout: "Logout",
        updateProfile: "Update Profile",
        profilePicture: "Profile Picture",
        update: "Update Profile",
        bio: "Short Biography",
        manifesto: "Campaign Manifesto",
        education: "Education / Qualifications",
        socials: "Social Media Links",
        save: "Save Changes",
        cancel: "Cancel",
        viewManifesto: "View Manifesto",
        votingRules: "Important Voting Rules",
        iAccept: "I Accept, Proceed to Vote",
        declineLogout: "Decline & Logout",
        overview: "Overview",
        voterRequests: "Voter Requests",
        candidateRequests: "Candidate Requests",
        approvedVoters: "Approved Voters",
        approvedCandidates: "Approved Candidates",
        subAdmins: "Sub-Admins",
        status: "Status",
        action: "Action",
        remove: "Remove",
        createSubAdmin: "Create Sub-Admin",
        // Hero & Features
        heroTitle: "Vote from Anywhere, Anytime. Safe & Secure.",
        heroDesc: "Experience the future of democracy with our blockchain-secured, AI-powered online voting platform.",
        voteBtn: "Vote Now",
        secureTitle: "100% Secure",
        secureDesc: "Built with enterprise-grade security protocols to ensure your vote is safe, anonymous, and counted.",
        fastTitle: "Fast & Easy",
        fastDesc: "Vote in seconds from your mobile or desktop. No queues, no paperwork, just seamless democracy.",
        accessTitle: "Accessible",
        accessDesc: "Whether you're domestic or overseas, exercise your right to vote without geographic barriers.",
        selectRole: "Select Login Role",
        backToRole: "← Back",
        adminId: "Admin ID",
        voterLoginDesc: "Login with Aadhaar to vote.",
        candidateLoginDesc: "Login to manage your campaign.",
        adminLoginDesc: "Login to manage elections.",
        facebook: "Facebook",
        twitter: "Twitter",
        instagram: "Instagram",
        website: "Website"
    },
    ta: {
        title: "ஆன்லைன் வாக்களிப்பு",
        home: "முகப்பு",
        login: "உள்நுழைய",
        signup: "பதிவு செய்க",
        vote: "வாக்களிக்க",
        results: "முடிவுகள்",
        welcome: "அதிகாரப்பூர்வ ஆன்லைன் வாக்களிப்பு முறைமைக்கு வரவேற்கிறோம்",
        voter: "வாக்காளர்",
        candidate: "வேட்பாளர்",
        admin: "நிர்வாகி",
        aadhaar: "ஆதார் எண்",
        password: "கடவுச்சொல்",
        mobile: "கைபேசி எண்",
        submit: "சமர்ப்பிக்கவும்",
        name: "முழு பெயர்",
        dob: "பிறந்த தேதி",
        party: "கட்சி பெயர்",
        ideology: "சித்தாந்தம்",
        photo: "புகைப்படம் பதிவேற்றவும்",
        approve: "ஏற்றுக்கொள்",
        reject: "நிராகரி",
        pending: "நிலுவையில் உள்ள கோரிக்கைகள்",
        publish: "முடிவுகளை வெளியிடவும்",
        otp: "OTP ஐ உள்ளிடவும்",
        verify: "சரிபார்க்கவும்",
        verifyVote: "சரிபார்த்து வாக்களிக்கவும்",
        alreadyVoted: "நீங்கள் ஏற்கனவே வாக்களித்துவிட்டீர்கள்.",
        votingOpen: "வாக்களிப்பு திறக்கப்பட்டுள்ளது!",
        selectLang: "மொழியதைத் தேர்ந்தெடுக்கவும்",
        candidateId: "வேட்பாளர் ஐடி",
        email: "மின்னஞ்சல் முகவரி",
        chooseType: "பதிவு வகையைத் தேர்வு செய்யவும்",
        voterSignupDesc: "வாக்களிக்க பதிவு செய்யவும்.",
        candidateSignupDesc: "தேர்தலில் போட்டியிட பதிவு செய்யவும்.",
        loginDesc: "உங்கள் டாஷ்போர்டை அணுகவும்.",
        resultsPublished: "தேர்தல் முடிவுகள் வெளியிடப்பட்டன!",
        resultsPending: "முடிவுகள் நிலுவையில் உள்ளன ... தேர்தல் நடைபெற்று வருகிறது.",
        adminDashboard: "நிர்வாக குழு",
        noData: "தரவு ஏதும் இல்லை.",
        authOptions: "போர்ட்டலை அணுகவும்",
        authDesc: "நீங்கள் புதியவரா அல்லது ஏற்கனவே உள்ள பயனரா?",
        castYourVote: "உங்கள் வாக்கைச் செலுத்துங்கள்",
        logout: "வெளியேறு",
        updateProfile: "சுயவிவரத்தைப் புதுப்பிக்கவும்",
        profilePicture: "சுயவிவரப் படம்",
        update: "புதுப்பிக்கவும்",
        bio: "சுய குறிப்பு",
        manifesto: "தேர்தல் அறிக்கை",
        education: "கல்வித் தகுதி",
        socials: "சமூக ஊடக இணைப்புகள்",
        save: "சேமி",
        cancel: "ரத்து செய்",
        viewManifesto: "தேர்தல் அறிக்கையைப் பார்க்கவும்",
        votingRules: "முக்கிய வாக்களிப்பு விதிகள்",
        iAccept: "நான் ஏற்கிறேன், வாக்களிக்க",
        declineLogout: "நிராகரி & வெளியேறு",
        overview: "கண்ணோட்டம்",
        voterRequests: "வாக்காளர் கோரிக்கைகள்",
        candidateRequests: "வேட்பாளர் கோரிக்கைகள்",
        approvedVoters: "அங்கீகரிக்கப்பட்ட வாக்காளர்கள்",
        approvedCandidates: "அங்கீகரிக்கப்பட்ட வேட்பாளர்கள்",
        subAdmins: "துணை நிர்வாகிகள்",
        status: "நிலை",
        action: "செயல்",
        remove: "அகற்று",
        createSubAdmin: "துணை நிர்வாகியை உருவாக்கவும்",
        // Hero & Features
        heroTitle: "எங்கிருந்தும், எப்போது வேண்டுமானாலும் வாக்களியுங்கள்.",
        heroDesc: "எங்கள் பிளாக்செயின்-பாதுகாக்கப்பட்ட ஆன்லைன் வாக்களிப்பு தளத்துடன் ஜனநாயகத்தின் எதிர்காலத்தை அனுபவிக்கவும்.",
        voteBtn: "இப்போது வாக்களிக்கவும்",
        secureTitle: "100% பாதுகாப்பானது",
        secureDesc: "உங்கள் வாக்கு பாதுகாப்பானது மற்றும் கணக்கிடப்படுவதை உறுதி செய்வதற்கான நிறுவனத் தர பாதுகாப்பு.",
        fastTitle: "வேகமான & எளிதானது",
        fastDesc: "நொடிகளில் வாக்களியுங்கள். வரிசைகள் இல்லை, காகிதங்கள் இல்லை.",
        accessTitle: "அணுகக்கூடியது",
        accessDesc: "புவியியல் தடைகள் இல்லாமல் உங்கள் வாக்குரிமையை செலுத்துங்கள்.",
        selectRole: "வாக்காளர் பாத்திரத்தைத் தேர்ந்தெடுக்கவும்",
        backToRole: "← பின்செல்",
        adminId: "நிர்வாக ஐடி",
        voterLoginDesc: "வாக்களிக்க ஆதார் மூலம் உள்நுழையவும்.",
        candidateLoginDesc: "பிரச்சாரத்தை நிர்வகிக்க உள்நுழையவும்.",
        adminLoginDesc: "தேர்தலை நிர்வகிக்க உள்நுழையவும்.",
        facebook: "ஃபேஸ்புக்",
        twitter: "ட்விட்டர்",
        instagram: "இன்ஸ்டாகிராம்",
        website: "இணையதளம்"
    },
    hi: {
        title: "ऑनलाइन वोटिंग",
        home: "मुखपृष्ठ",
        login: "लॉग इन करें",
        signup: "साइन अप करें",
        vote: "वोट दें",
        results: "परिणाम",
        welcome: "आधिकारिक ऑनलाइन वोटिंग सिस्टम में आपका स्वागत है",
        voter: "मतदाता",
        candidate: "उम्मीदवार",
        admin: "प्रशासक",
        aadhaar: "आधार संख्या",
        password: "पासवर्ड",
        mobile: "मोबाइल नंबर",
        submit: "जमा करें",
        name: "पूरा नाम",
        dob: "जन्म की तारीख",
        party: "पार्टी का नाम",
        ideology: "विचारधारा",
        photo: "फोटो अपलोड करें",
        approve: "स्वीकृत करें",
        reject: "अस्वीकार करें",
        pending: "लंबित अनुरोध",
        publish: "परिणाम प्रकाशित करें",
        otp: "ओटीपी दर्ज करें",
        verify: "सत्यापित करें",
        verifyVote: "सत्यापित करें और वोट दें",
        alreadyVoted: "आप पहले ही मतदान कर चुके हैं।",
        votingOpen: "मतदान खुला है!",
        selectLang: "भाषा चुने",
        candidateId: "उम्मीदवार आईडी",
        email: "ईमेल पता",
        chooseType: "पंजीकरण प्रकार चुनें",
        voterSignupDesc: "वोट डालने के लिए पंजीकरण करें।",
        candidateSignupDesc: "चुनाव लड़ने के लिए पंजीकरण करें।",
        loginDesc: "अपने डैशबोर्ड तक पहुंचें।",
        resultsPublished: "चुनाव परिणाम प्रकाशित!",
        resultsPending: "परिणाम लंबित हैं... चुनाव जारी है।",
        adminDashboard: "एडमिन डैशबोर्ड",
        noData: "कोई डेटा उपलब्ध नहीं है।",
        authOptions: "पोर्टल तक पहुंचें",
        authDesc: "क्या आप नए या मौजूदा उपयोगकर्ता हैं?",
        castYourVote: "अपना वोट डालें",
        logout: "लॉग आउट",
        updateProfile: "प्रोफ़ाइल अपडेट करें",
        profilePicture: "प्रोफ़ाइल चित्र",
        update: "अपडेट करें",
        bio: "संक्षिप्त परिचय",
        manifesto: "चुनाव घोषणापत्र",
        education: "शिक्षा / योग्यता",
        socials: "सोशल मीडिया लिंक",
        save: "सहेजें",
        cancel: "रद्द करें",
        viewManifesto: "घोषणापत्र देखें",
        votingRules: "महत्वपूर्ण मतदान नियम",
        iAccept: "मैं स्वीकार करता हूँ, वोट दें",
        declineLogout: "अस्वीकार और लॉगआउट",
        overview: "अवलोकन",
        voterRequests: "मतदाता अनुरोध",
        candidateRequests: "उम्मीदवार अनुरोध",
        approvedVoters: "स्वीकृत मतदाता",
        approvedCandidates: "स्वीकृत उम्मीदवार",
        subAdmins: "उप-प्रशासक",
        status: "स्थिति",
        action: "कार्रवाई",
        remove: "हटाएं",
        createSubAdmin: "उप-प्रशासक बनाएँ",
        // Hero & Features
        heroTitle: "कहीं से भी, कभी भी वोट करें। सुरक्षित।",
        heroDesc: "हमारे ब्लॉकचेन-सुरक्षित ऑनलाइन वोटिंग प्लेटफॉर्म के साथ लोकतंत्र के भविष्य का अनुभव करें।",
        voteBtn: "अभी वोट दें",
        secureTitle: "100% सुरक्षित",
        secureDesc: "आपका वोट सुरक्षित और गोपनीय है, यह सुनिश्चित करने के लिए उच्च सुरक्षा।",
        fastTitle: "तेज़ और आसान",
        fastDesc: "अपने मोबाइल या डेस्कटॉप से सेकंडों में वोट करें। कोई कतार नहीं।",
        accessTitle: "सुलभ",
        accessDesc: "भौगोलिक बाधाओं के बिना अपने मताधिकार का प्रयोग करें।",
        selectRole: "भूमिका चुनें",
        backToRole: "← वापस",
        adminId: "एडमिन आईडी",
        voterLoginDesc: "वोट करने के लिए आधार से लॉगिन करें।",
        candidateLoginDesc: "अभियान का प्रबंधन करने के लिए लॉगिन करें।",
        adminLoginDesc: "चुनाव प्रबंधन के लिए लॉगिन करें।",
        facebook: "फेसबुक",
        twitter: "ट्विटर",
        instagram: "इंस्टाग्राम",
        website: "वेबसाइट"
    }
};

function setLanguage(lang) {
    localStorage.setItem('lang', lang);
    document.documentElement.lang = lang;
    document.querySelectorAll('[data-lang]').forEach(el => {
        const key = el.getAttribute('data-lang');
        if (translations[lang][key]) {
            if (el.tagName === 'INPUT') {
                el.placeholder = translations[lang][key];
            } else {
                el.textContent = translations[lang][key];
            }
        }
    });
}

document.addEventListener('DOMContentLoaded', () => {
    const savedLang = localStorage.getItem('lang') || 'en';
    const langSelect = document.getElementById('langSelect');
    if (langSelect) {
        langSelect.value = savedLang;
        langSelect.addEventListener('change', (e) => setLanguage(e.target.value));
    }
    setLanguage(savedLang);
});
